<<<<<<< HEAD

development:
  adapter: postgresql
  database: flipbook_development 
  pool: 5


test:
  adapter: postgresql
  database: flipbook_test
  pool: 5


production:
  adapter: postgresql
  database: flipbook_production
  pool: 5


