development:
  adapter: postgresql
  database: flips_development
  host: localhost
  pool: 5



test:
  adapter: postgresql
  database: flips_test
  host: localhost
  pool: 5

production:
  adapter: postgresql
  database: flips_production
  host: localhost
  pool: 5
 
  
