<<<<<<< HEAD
development:
  adapter: postgresql
  database: flips_development
  host: localhost
  pool: 5



test:
  adapter: postgresql
  database: flips_test
  host: localhost
  pool: 5

production:
  adapter: postgresql
  database: flips_production
  host: localhost
  pool: 5
 
  
=======
<<<<<<< HEAD

development:
  adapter: postgresql
  database: flipbook_development 
  pool: 5


test:
  adapter: postgresql
  database: flipbook_test
  pool: 5


production:
  adapter: postgresql
  database: flipbook_production
  pool: 5


>>>>>>> 9c4834e89589f59f76f2dce44ed9143ed524675c
